package javaapplication2;
import java.util.regex.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rcc
 */
public class SlotUI extends javax.swing.JFrame {

    /**
     * Creates new form SlotUI
     */
    public SlotUI() {
        initComponents();
        PlayUI.setVisible(false);
        GameUI.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GameLabel = new javax.swing.JLabel();
        StartBtn = new javax.swing.JButton();
        ContinueBtn = new javax.swing.JButton();
        HelpBtn = new javax.swing.JButton();
        PlayUI = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        GameUI = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        availCredit = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setResizable(false);

        GameLabel.setText("Casino Style Slots");

        StartBtn.setText("Start");
        StartBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartBtnMouseClicked(evt);
            }
        });

        ContinueBtn.setText("Continue");

        HelpBtn.setText("Help");
        HelpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpBtnActionPerformed(evt);
            }
        });

        PlayUI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        PlayUI.setPreferredSize(new java.awt.Dimension(575, 450));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Time to Play!");

        jLabel2.setText("What is your name?");

        jLabel3.setText("Enter email address");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Ready?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("!");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("!");

        javax.swing.GroupLayout PlayUILayout = new javax.swing.GroupLayout(PlayUI);
        PlayUI.setLayout(PlayUILayout);
        PlayUILayout.setHorizontalGroup(
            PlayUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayUILayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(PlayUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(PlayUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PlayUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2)))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        PlayUILayout.setVerticalGroup(
            PlayUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayUILayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PlayUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PlayUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        PlayUI.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PlayUI.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PlayUI.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PlayUI.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PlayUI.setLayer(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PlayUI.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PlayUI.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PlayUI.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        GameUI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GameUI.setMaximumSize(new java.awt.Dimension(575, 450));
        GameUI.setPreferredSize(new java.awt.Dimension(575, 450));

        jLabel4.setText("jLabel4");

        availCredit.setText("Credits");

        jButton2.setText("Bet 3 Lines");

        jButton3.setText("Bet 1 Line");

        jButton4.setText("Max Bet");

        javax.swing.GroupLayout GameUILayout = new javax.swing.GroupLayout(GameUI);
        GameUI.setLayout(GameUILayout);
        GameUILayout.setHorizontalGroup(
            GameUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameUILayout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addGroup(GameUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GameUILayout.createSequentialGroup()
                        .addGroup(GameUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GameUILayout.createSequentialGroup()
                        .addComponent(availCredit)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GameUILayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))))
        );
        GameUILayout.setVerticalGroup(
            GameUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameUILayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(availCredit)
                .addGap(36, 36, 36)
                .addComponent(jButton3)
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addGap(57, 57, 57)
                .addComponent(jButton4)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        GameUI.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        GameUI.setLayer(availCredit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        GameUI.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        GameUI.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        GameUI.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(StartBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GameLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ContinueBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HelpBtn)))
                .addGap(186, 186, 186))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PlayUI, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(GameUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(85, 85, 85)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(GameLabel)
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartBtn)
                    .addComponent(ContinueBtn)
                    .addComponent(HelpBtn))
                .addContainerGap(214, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PlayUI, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(GameUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(83, 83, 83)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartBtnMouseClicked
        // TODO add your handling code here:
        //set buttons and title not visible
        ContinueBtn.setVisible(false);
        GameLabel.setVisible(false);
        HelpBtn.setVisible(false);
        StartBtn.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        PlayUI.setVisible(true);
    }//GEN-LAST:event_StartBtnMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //check to see if input was made
            System.out.println(jTextField1.getText());
            System.out.println(jTextField2.getText());
            //verify if input is valid
            boolean nameisValid = fname(jTextField1.getText());
            boolean emailValid = isEmail(jTextField2.getText());
            //Check if name is valid!
            System.out.println(nameisValid);
            System.out.println(emailValid);
            
            //display next screen if valid input
            if(nameisValid&&emailValid){
                PlayUI.setVisible(false);
                GameUI.setVisible(true);
                jLabel4.setText("Hey "+jTextField1.getText()+", Let's Play!");
                jLabel4.setVisible(true);
            }
            //handle '!' marker for bad input
            if(nameisValid != true){
                jLabel5.setVisible(true);
            }
            if(emailValid != true){
                jLabel6.setVisible(true);
            }
            if(nameisValid == true){
                jLabel5.setVisible(false);
            }
            if(emailValid == true){
                jLabel6.setVisible(false);
            }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void HelpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HelpBtnActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    
    //regex functions
    public static boolean fname(String check){
        return check.matches("[A-Z][a-zA-Z]*");
    }
    public static boolean isEmail(String check){
        return check.matches("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
		+ "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ContinueBtn;
    private javax.swing.JLabel GameLabel;
    private javax.swing.JLayeredPane GameUI;
    private javax.swing.JButton HelpBtn;
    private javax.swing.JLayeredPane PlayUI;
    private javax.swing.JButton StartBtn;
    private javax.swing.JLabel availCredit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
